# Update the vars/aws_vars.yml file according to your AWS and VPC resource id's
---

- name: AWS | Get the latest Ubuntu precise AMI
  ec2_ami_search: distro=ubuntu release=precise region={{ region }}
  register: ubuntu_ami


- name: AWS | Launch EC2 instance in VPC
  local_action:
    module: ec2
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    group_id: "{{ security_groups }}"
    image: "{{ ubuntu_ami.ami }}"
    vpc_subnet_id: "{{ subnet }}"
    volumes: "{{ volumes }}"
    instance_type: "{{ type }}"
    wait: yes
    instance_tags:
      Name: "ansible_test_{{ tags.role }}"
      role: "{{ tags.role }}"
    count: "{{ count }}"
  register: ec2


- name: Add new instance to host group
  local_action: add_host hostname={{ item.private_ip }} groupname=launched
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
